### PR TITLE
Do not include comment's block end in the error message

### LINKED ISSUE #64: Issue caused by a single-line block format comment is printed incorrectly
When the comment is formatted like this:
```PHP
/** TODO: 2000-12-08 Fix me */
```

then the error message includes `*/`, but it should be omitted.

Actual error message:
```
Expired on 2000-12-08: Fix me */.
```

Expected error message:
```
Expired on 2000-12-08: Fix me.
```

### PR DESCRIPTION
**Pull request by EmilMassey**
Closes #64

### CODE REVIEW

File: tests/data/bug64.php [hunk 1]
```diff
@@ -0,0 +1,11 @@
+<?php
```
Comment (staabm) [inline tests/data/bug64.php:1]: Please add a sample with `*` in the middle of commment

**Comment by staabm** [comment]
thank you
