### PR TITLE
Use `vendor/composer/installed.php` in TodoByPackageVersionRule.php

### LINKED ISSUE #146: TodoByPackageVersionRule uses PHPStan's InstalledVersions class
Thanks for this amazing extension.

I just noticed that the TodoByPackageVersionRule is not working properly.

It's reading the installed versions from `phar:///Volumes/CS/www/cosmos/vendor/phpstan/phpstan/phpstan.phar/vendor/composer/InstalledVersions.php`

See

Image

This makes checks like this:
```
// TODO symfony/console:v7.3.0 test this should trigger
```

Worthless, because they are always compared to PHPStan's version of Console, which is:
https://github.com/phpstan/phpstan-src/blob/c0f2e9e9235db973784d88b107bc8c14ecb647d0/composer.json#L42

### PR DESCRIPTION
**Pull request by ruudk**
Fixes #146

### CODE REVIEW

**Comment by ruudk** [comment]
@staabm I think the failing test, is actually a wrong test. How could that ever have worked? Given that `composer.json` requires `phpunit ^9 || ^10.5`. So the `TODO: phpunit/phpunit:<10` error can only happen on older PHP versions where it's even allowed.

**Comment by ruudk** [comment]
Yes I believe that is the case. Shall I fix the test?

**Comment by staabm** [comment]
yes please do

**Comment by ruudk** [comment]
@staabm Done

File: tests/data/packageVersion.php [hunk 1]
```diff
@@ -11,7 +11,6 @@
 // TODO: not-installed/package:<5 this should error because package is not in composer.json
 
 // TODO: phpunit/phpunit:<9
-// TODO: phpunit/phpunit:<10
```
Comment (staabm) [inline tests/data/packageVersion.php:14]: just realized after merge: next time don't delete such line but make it empty. that way you don't need unrelated changes in test expectations

**Comment by staabm** [comment]
thank you!
